### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by Mantxurreta** [GPUOpen-Tools/RCP#16]
Hello,
After I get a satisfactory build I do not find executables.
Process:
git clone https://github.com/GPUOpen-Tools/RCP.git
cd RCP
python Scripts/UpdateCommon.py
cd Build/Linux/
sh ./build_rcp.sh skip-32bitbuild skip-hsaprofiler
------
NOTE:
hsa 64bit fails if I do not skip it
I try to install ROCm but it seem to interfere with my AMDGPU driver installed 18.30.
--------
With the process above I get the return:
----------- End building ----------------- 
Fr 31. Aug 21:10:06 CEST 2018
========================================== 
*** SUCCESS ***
Build Common, 64-bit...
Build DeviceInfo, 64-bit...
Build CLCommon, 64-bit...
Build CLProfileAgent, 64-bit...
Build CLTraceAgent, 64-bit...
Build CLOccupancyAgent, 64-bit...
Build ProfileDataParser, 64-bit...
Build sprofile, 64-bit...
Build PreloadXInitThreads, 64-bit...

---------
Content of the folder RCP/Output/bin
total 94296
drwxr-xr-x 2 myuser myuser     4096 Aug 31 21:10 ./
drwxr-xr-x 6 myuser myuser     4096 Aug 31 21:10 ../
-rwxr-xr-x 1 myuser myuser 12457628 Aug 31 21:10 libGPUPerfAPICL32.so*
-rwxr-xr-x 1 myuser myuser 23332448 Aug 31 21:10 libGPUPerfAPICL.so*
-rwxr-xr-x 1 myuser myuser 12097328 Aug 31 21:10 libGPUPerfAPICounters32.so*
-rwxr-xr-x 1 myuser myuser 22962744 Aug 31 21:10 libGPUPerfAPICounters.so*
-rwxr-xr-x 1 myuser myuser  4151928 Aug 31 21:10 libRCPCLOccupancyAgent.so*
-rwxr-xr-x 1 myuser myuser  4463464 Aug 31 21:10 libRCPCLProfileAgent.so*
-rwxr-xr-x 1 myuser myuser  5170752 Aug 31 21:10 libRCPCLTraceAgent.so*
-rwxr-xr-x 1 myuser myuser     7584 Aug 31 21:10 libRCPPreloadXInitThreads.so*
-rwxr-xr-x 1 myuser myuser  4747600 Aug 31 21:10 libRCPProfileDataParser.so*
-rwxr-xr-x 1 myuser myuser  7022744 Aug 31 21:10 rcprof*
-rwxr-xr-x 1 myuser myuser    24088 Aug 31 21:10 VkStableClocks*
---------

The log is in an attached file.
Thank you for your help.

[RCP_Build_problem.log](https://github.com/GPUOpen-Tools/RCP/files/2341337/RCP_Build_problem.log)

**Comment by chesik-amd** [comment]
**After I get a satisfactory build I do not find executables.**

It looks like your build succeeded. Your directory listing above shows that you have the "rcprof" executable.

**Comment by Mantxurreta** [comment]
My folder explorer did not recognise it as a program and I didnt distinguish it from the ".so" files. Therefore I assumed that I did not succeed in building it. 
Thank you.
