### ISSUE TITLE
When will we get a ROCm 1.9 compatible release?

### ISSUE THREAD

**Issue by 949f45ac** [GPUOpen-Tools/RCP#23]
RCP is a great tool!
When can I hope to be able to use it with ROCm 1.9?

**Comment by jlgreathouse** [comment]
Hi @949f45ac 

With the release of RCP 5.6 and ROCm 2.0, I believe that RCP ocne again works with ROCm. @chesik-amd to verify. :)

**Comment by chesik-amd** [comment]
Yes, thanks @jlgreathouse.  One of the updates to ROCm 1.9 fixed the incompatibilities with RCP. But RCP 5.6 and ROCm 2.0 work well together too.
