### ISSUE TITLE
Profiling a Python script

### ISSUE THREAD

**Issue by masahi** [GPUOpen-Tools/RCP#5]
Hi, I have a python script that calls HSA kernels, and I want to profile this script. 

Ideally, I want to do something like:
`$ rocm-profiler -A -w . python style_transfer.py`

But I am getting this error message at the moment:
`Process failed to run. Make sure you have specified the correct path.` 

Is there a way to do what I want? 

It seems CodeXL can profile python scripts, by specifying the executable name as "python" and setting the script name to the command line argument.

**Comment by chesik-amd** [comment]
Can you check if specifying the full path to python (/usr/bin/python) makes a difference here?

**Comment by masahi** [comment]
yes, specifying the full path to python executable solved my issue.

Thanks.
