### ISSUE TITLE
Remove RCP by script

### ISSUE THREAD

**Issue by wei-yuan** [GPUOpen-Tools/RCP#6]
Hi, 
I had installed RCP using `build_rcp.sh` several weeks ago on my Ubuntu 16.04 pc
Now, I want to reinstall it. 
Before that, I have to uninstall RCP.
I've noticed that there is no uninstall shell script in RCP repo

## My Question is
Is there any proper way to uninstall RCP?  
Or I only can remove it manually?  
But how?
Thank you for your time

**Comment by chesik-amd** [comment]
RCP does not have any install/uninstall scripts. "build_rcp.sh" is the build script.  You can execute "build_rcp.sh clean" to remove any artifacts from previous builds, and then you can execute the build script again to rebuild RCP.

**Comment by wei-yuan** [comment]
@chesik-amd  Thank you for your clear and informative apply!
Have a great day!
