### ISSUE TITLE
scons not listed as a dependency, but is required. 

### ISSUE THREAD

**Issue by Mandrewoid** [GPUOpen-Tools/RCP#7]
Build/Linux/build_rcp.sh invokes scons, but nowhere is it listed as required. If you start with a clean install of Ubuntu, you will get confusing error that lists "Build arguments passed to scons" but obviously they weren't, if you don't have scons.

Command line arguments passed to build_rcp.sh: 
RCPROOT=/home/crews/RCP/Build/Linux/../..
=====Building Radeon Compute Profiler======

Building infra projects
===========================
Build arguments passed to scons: 
========================================== 
----------- Start building --------------- 
Sun Feb  4 10:44:00 EST 2018
========================================== 
scons -C /home/crews/RCP/Build/Linux/../../Build/Linux CXL_prefix=/home/crews/RCP/Build/Linux/../../Output CXL_build_type=static 
*** ERROR during the build of the 64 bit framework ***
========================================== 
(scons -C /home/crews/RCP/Build/Linux/../../Build/Linux CXL_prefix=/home/crews/RCP/Build/Linux/../../Output CXL_arch=x86 CXL_build_type=static )
*** ERROR during the build of the 32 bit framework ***
========================================== 
----------- End building ----------------- 
Sun Feb  4 10:44:00 EST 2018
========================================== 
*** ERROR ***
*** the build failed - see the logs for details ***

sudo apt-get install scons fixed issue. Should be listed as a prerequisite along with python

**Comment by chesik-amd** [comment]
Thanks for pointing this out.  We will update the list of prerequisites in BUILD.md to include scons.
