### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by preda** [GPUOpen-Tools/RCP#8]
I tried a build an it fails as below:

/home/preda/Common/Src/AMDTOSWrappers/src/common/osCpuid.cpp: In constructor 'osCpuid::osCpuid()':
/home/preda/Common/Src/AMDTOSWrappers/src/common/osCpuid.cpp:53:20: error: '*((void*)& info +12)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     osCpuidParam_t info[MAX_CPUID_REGS];
                    ^~~~
/home/preda/Common/Src/AMDTOSWrappers/src/common/osCpuid.cpp:53:20: error: '*((void*)& info +8)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
/home/preda/Common/Src/AMDTOSWrappers/src/common/osCpuid.cpp:53:20: error: '*((void*)& info +4)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
/home/preda/Common/Src/AMDTOSWrappers/src/common/osCpuid.cpp:70:5: error: 'info' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     if (info[EAX] > 0)
     ^~
cc1plus: all warnings being treated as errors

**Comment by acowley** [comment]
Though I, too, can not build `rcp`, I was able to get past this by removing `-Werror` from `Build/Linux/CXL_init.py`.

**Comment by chesik-amd** [comment]
This should now be fixed.  You should now be able to build RCP with gcc7.  You'll need to make sure you have the latest sources from the common-src-AMDTOSWrappers repo as well (running Scripts/UpdateCommon.py should get the latest changes from there)
